// Panel metadata — separated from lazy imports to avoid circular dependencies with ToolHub.
// ToolHub imports from here; panelRegistry re-exports from here.

export interface PanelMenuOption { value: string; label: string; description?: string }
export interface PanelMenuGroup { category: string; color: string; items: PanelMenuOption[] }

export const PANEL_NAMES: Record<string, string> = {
  cui: 'Chat',
  'cui-lite': 'Chat',
  browser: 'Browser',
  preview: 'File Preview',
  notes: 'Notes',
  images: 'Images',
  mission: 'Mission Control',
  'mission-chat': 'Mission Chat',
  office: 'Virtual Office',
  'virtual-office': 'Virtual Office',
  gmail: 'Virtual Office',
  knowledge: 'Knowledge',
  'knowledge-fullscreen': 'Knowledge',
  'admin-wr': 'Werking Report Admin',
  linkedin: 'LinkedIn Marketing',
  'qa-dashboard': 'QA Dashboard',
  'bridge-monitor': 'Bridge Monitor',
  'infisical-monitor': 'Infisical Monitor',
  'repo-dashboard': 'Git & Pipeline Monitor',
  watchdog: 'Dev Server Watchdog',
  infrastructure: 'Dev Server Watchdog',
  'background-ops': 'Background Ops',
  'conversation-queue': 'Conversation Queue',
  maintenance: 'Maintenance',
  'input-audit': 'Input Audit',
  architecture: 'Architecture Explorer',
  'report-builder': 'Report Builder',
  'prompt-explorer': 'Workflow Explorer',
  'business-angel': 'Business Angel',
  'privat-angel': 'Privat Angel',
  'business-docs': 'Business Docs',
  'my-tasks': 'My Tasks',
  'activity-feed': 'Activity Feed',
  'partner-inbox': 'Partner Inbox',
  feedback: 'Feedback',
  'team-status': 'Team Status',
  'uploads': 'Uploads',
  'calendar': 'Kalender',
  'mail': 'Mail',
  'tool-hub': 'Tool Hub',
  'error-monitor': 'Error Monitor',
  'partner-server': 'Partner Server Health',
  'sandbox-privat-angel': 'Privat-Assistent (Sandbox)',
  'sandbox-business-angel': 'Business-Assistent (Sandbox)',
};

export const PANEL_MENU_OPTIONS: PanelMenuGroup[] = [
  {
    category: 'Workspace',
    color: '#7aa2f7',
    items: [
      { value: 'cui', label: 'Chat', description: 'Konversation mit der KI — Aufträge stellen, Sub-Sessions starten, Antworten lesen.' },
      { value: 'browser', label: 'Browser', description: 'Eingebetteter Browser für Apps und Tools — direkt im Layout, ohne Tab-Wechsel.' },
      { value: 'tool-hub', label: 'Tool Hub', description: 'Übersicht aller verfügbaren Panels — schneller Einstieg per Klick.' },
      { value: 'preview', label: 'File Preview', description: 'Markdown- und Dokument-Vorschau — Strategien, Specs, Notizen rendern.' },
      { value: 'notes', label: 'Notes', description: 'Persönliche und geteilte Notizen — pro Workspace abgelegt.' },
      { value: 'images', label: 'Images', description: 'Bild-Galerie für Screenshots und Uploads des aktuellen Workspaces.' },
    ],
  },
  {
    category: 'Übersicht',
    color: '#bb9af7',
    items: [
      { value: 'mission', label: 'Mission Control', description: 'Steuerzentrale für alle Sessions — starten, beenden, Layouts setzen.' },
      { value: 'mission-chat', label: 'Mission Chat', description: 'Quer-Chat über alle Sessions hinweg — analysiert, synchronisiert, fragt nach.' },
      { value: 'conversation-queue', label: 'Conversation Queue', description: 'Warteschlange laufender und geplanter KI-Konversationen.' },
      { value: 'office', label: 'Virtual Office', description: 'Visualisierung wer woran arbeitet — Sessions, Tasks, Status auf einen Blick.' },
    ],
  },
  {
    category: 'Analyse',
    color: '#7dcfff',
    items: [
      { value: 'qa-dashboard', label: 'QA Dashboard', description: 'Test-System: Szenarien, Reports, Pyramide, Coverage. Beschreibungen + Wissensbasis inklusive.' },
      { value: 'architecture', label: 'Architecture Explorer', description: 'Repo- und Modul-Architektur visualisieren — Abhängigkeiten und Schichten.' },
      { value: 'knowledge', label: 'Knowledge', description: 'Wissensbasis: gesammelte Erkenntnisse aus Sessions, Memory und Docs.' },
      { value: 'report-builder', label: 'Report Builder', description: 'Berichte zusammenstellen aus Daten und Texten — fürs Management.' },
      { value: 'prompt-explorer', label: 'Workflow Explorer', description: 'Workflow-Manifeste durchsuchen und prüfen — Energy, Safety, Report.' },
    ],
  },
  {
    category: 'Monitoring',
    color: '#ff9e64',
    items: [
      { value: 'error-monitor', label: 'Error Monitor', description: 'Aktuelle Fehler aus allen Apps — Stack-Traces, Häufungen, Triage.' },
      { value: 'bridge-monitor', label: 'Bridge Monitor', description: 'AI-Bridge-Status: Modelle, Quoten, laufende Anfragen, Fehlerquote.' },
      { value: 'repo-dashboard', label: 'Git & Pipeline Monitor', description: 'Status aller Repos: Branches, offene PRs, Build-Status, Deploy-Stand.' },
      { value: 'infisical-monitor', label: 'Infisical Monitor', description: 'Secret-Stand pro Projekt — Drift zwischen dev/prod erkennen.' },
      { value: 'watchdog', label: 'Dev Server Watchdog', description: 'Laufende Prozesse, Ports, Speicher und CPU des Dev-Servers.' },
    ],
  },
  {
    category: 'Admin',
    color: '#f7768e',
    items: [
      { value: 'admin-wr', label: 'Werking Report Admin', description: 'WerkING-Report Daten verwalten: User, Reports, Stammdaten.' },
      { value: 'business-angel', label: 'Business Angel', description: 'Geschäftliche Anfragen und To-Dos automatisch beantworten lassen.' },
      { value: 'privat-angel', label: 'Privat Angel', description: 'Privater Assistent für persönliche Aufgaben und Korrespondenz.' },
      { value: 'sandbox-business-angel', label: 'Business-Assistent (Sandbox)', description: 'Business-Assistent mit direktem Daemon-Zugriff auf die Business-Wissensbase.' },
      { value: 'sandbox-privat-angel', label: 'Privat-Assistent (Sandbox)', description: 'Persönlicher Assistent mit direktem Daemon-Zugriff auf die Privat-Wissensbase.' },
      { value: 'background-ops', label: 'Background Ops', description: 'Hintergrund-Jobs anschauen: Cron, Sync-Bots, periodische Tasks.' },
      { value: 'maintenance', label: 'Maintenance', description: 'Wartungs-Routinen ausführen: Dokumente, Caches, Aufräum-Skripte.' },
      { value: 'input-audit', label: 'Input Audit', description: 'Alle eigenen Eingaben über alle Sessions — Volltext-Suche, Zeitfilter.' },
      { value: 'linkedin', label: 'LinkedIn Marketing', description: 'LinkedIn-Posts planen, schreiben und veröffentlichen.' },
      { value: 'partner-server', label: 'Partner Server Health', description: 'Status des Partner-Servers: Services, Sync-Stand, Logs.' },
    ],
  },
  {
    category: 'Partner',
    color: '#e0af68',
    items: [
      { value: 'partner-inbox', label: 'Nachrichten', description: 'Posteingang — Antworten von Rafael auf deine Fragen, Updates vom Team.' },
      { value: 'feedback', label: 'Feedback an Rafael', description: 'Verbesserungsvorschläge, Bugs oder Fragen einreichen — landet in Rafaels Inbox.' },
      { value: 'my-tasks', label: 'Aufgaben', description: 'Was als Nächstes ansteht — deine offenen Punkte und Reviews.' },
      { value: 'uploads', label: 'Dateien hochladen', description: 'Dokumente, Bilder, PDFs für deinen Chat hochladen.' },
      { value: 'business-docs', label: 'Produkt-Doku', description: 'Vision, Roadmap, Feature-Specs — was wird gerade gebaut und warum.' },
      { value: 'activity-feed', label: 'Aktivität', description: 'Was hat das System zuletzt gemacht — Sessions, Commits, Deploys.' },
      { value: 'calendar', label: 'Kalender', description: 'Termine und Deadlines — synchronisiert mit dem Konto-Kalender.' },
      { value: 'mail', label: 'Mail', description: 'E-Mail-Postfach — lesen, beantworten, Drafts vorbereiten.' },
      { value: 'calendar', label: 'Kalender', description: 'Termine und Deadlines — synchronisiert mit dem Konto-Kalender.' },
      { value: 'mail', label: 'Mail', description: 'E-Mail-Postfach — lesen, beantworten, Drafts vorbereiten.' },
    ],
  },
];
