#!/bin/bash
# ============================================================================
# CUI Partner Server — Infisical Setup
# ============================================================================
# Installs the Infisical API helper on a partner server so the CUI can load
# secrets from Infisical at startup (same as the dev-server).
#
# USAGE (from dev-server):
#   ./setup-partner-infisical.sh <partner-tailscale-ip>
#
# What this does:
#   1. Copies infisical-api.sh + get-token.py to partner
#   2. Copies the .auth-secret (JWT signing key)
#   3. Creates a partner-specific infisical-api.sh with LIMITED workspace IDs
#   4. Sources the helper from claude-user's .bashrc
#
# Prerequisites:
#   - Partner server is on the Tailscale network
#   - Partner can reach Infisical server (100.79.71.99)
#   - SSH access as root to partner
# ============================================================================
set -euo pipefail

TARGET="${1:-}"
if [ -z "$TARGET" ]; then
  echo "Usage: $0 <partner-tailscale-ip>"
  echo "Example: $0 100.119.199.86"
  exit 1
fi

INFISICAL_DIR="/root/.infisical"
PARTNER_INFISICAL_DIR="/home/claude-user/.infisical"

echo "========================================"
echo "  Setup Infisical → $TARGET"
echo "========================================"

# ── 1. Verify local Infisical setup ────────────────────────────────────
if [ ! -f "$INFISICAL_DIR/infisical-api.sh" ]; then
  echo "ERROR: $INFISICAL_DIR/infisical-api.sh not found on dev-server"
  exit 1
fi
if [ ! -f "$INFISICAL_DIR/get-token.py" ]; then
  echo "ERROR: $INFISICAL_DIR/get-token.py not found on dev-server"
  exit 1
fi
if [ ! -f "$INFISICAL_DIR/.auth-secret" ]; then
  echo "ERROR: $INFISICAL_DIR/.auth-secret not found on dev-server"
  exit 1
fi

# ── 2. Create directory on partner ──────────────────────────────────────
echo "[1/4] Creating $PARTNER_INFISICAL_DIR on partner..."
ssh "root@$TARGET" "mkdir -p $PARTNER_INFISICAL_DIR && chown claude-user:claude-user $PARTNER_INFISICAL_DIR && chmod 700 $PARTNER_INFISICAL_DIR"

# ── 3. Copy token generator ────────────────────────────────────────────
echo "[2/4] Copying get-token.py and .auth-secret..."
scp "$INFISICAL_DIR/get-token.py" "root@$TARGET:$PARTNER_INFISICAL_DIR/get-token.py"
scp "$INFISICAL_DIR/.auth-secret" "root@$TARGET:$PARTNER_INFISICAL_DIR/.auth-secret"
ssh "root@$TARGET" "chmod 600 $PARTNER_INFISICAL_DIR/.auth-secret && chown -R claude-user:claude-user $PARTNER_INFISICAL_DIR"

# ── 4. Create partner-specific infisical-api.sh ────────────────────────
# Partner gets ONLY the workspace IDs needed for CUI operation.
# NO production app workspaces, NO deploy secrets.
echo "[3/4] Creating partner infisical-api.sh (limited scope)..."

# Read workspace IDs from dev-server
source "$INFISICAL_DIR/infisical-api.sh" 2>/dev/null || true

cat > /tmp/partner-infisical-api.sh << PARTNER_API
#!/bin/bash
# =============================================================================
# INFISICAL API HELPER (Partner Server — Limited Scope)
# =============================================================================
# Auto-generated by setup-partner-infisical.sh
# Only contains workspace IDs needed for CUI operation.
# =============================================================================

export INFISICAL_URL="http://100.79.71.99"

_infisical_token() {
    python3 ${PARTNER_INFISICAL_DIR}/get-token.py 2>/dev/null
}

infisical_get_secret() {
    local WS_ID="\$1" ENV="\$2" NAME="\$3"
    local TOKEN=\$(_infisical_token)
    curl -s "\${INFISICAL_URL}/api/v3/secrets/raw/\${NAME}?workspaceId=\${WS_ID}&environment=\${ENV}&secretPath=/" \\
        -H "Authorization: Bearer \${TOKEN}" | python3 -c "
import sys, json
data = json.load(sys.stdin)
print(data.get('secret', {}).get('secretValue', 'NOT_FOUND'))
" 2>/dev/null
}

# fetch_infisical_secrets — bulk secret loading (used by build-and-start via load-app-env)
# Outputs: export KEY='value' lines (shlex-quoted, safe for eval/source)
fetch_infisical_secrets() {
  local ws_id="\$1" env_slug="\$2"
  python3 - "\$ws_id" "\$env_slug" << 'PYEOF'
import json, urllib.request, subprocess, sys, shlex, os
token_script = os.path.expanduser('~/.infisical/get-token.py')
if not os.path.exists(token_script):
    token_script = '/home/claude-user/.infisical/get-token.py'
token = subprocess.check_output(['python3', token_script]).decode().strip()
ws_id, env_slug = sys.argv[1], sys.argv[2]
req = urllib.request.Request(
    f'http://100.79.71.99/api/v3/secrets/raw?workspaceId={ws_id}&environment={env_slug}&secretPath=/',
    headers={'Authorization': f'Bearer {token}'}
)
try:
    resp = urllib.request.urlopen(req, timeout=10)
    data = json.loads(resp.read())
    count = 0
    for s in data.get('secrets', []):
        key = s['secretKey']
        val = s['secretValue']
        print(f'export {key}={shlex.quote(val)}')
        count += 1
    print(f'  Loaded {count} secrets from Infisical ({env_slug})', file=sys.stderr)
except Exception as e:
    print(f'  ERROR loading Infisical secrets: {e}', file=sys.stderr)
    sys.exit(1)
PYEOF
}

# get_infisical_ws_id — maps app_id to workspace ID (used by load-app-env)
get_infisical_ws_id() {
  local app_id="\$1"
  case "\$app_id" in
    engelmann)        echo "${INFISICAL_WS_ENGELMANN}" ;;
    werking-report)   echo "${INFISICAL_WS_WERKING_REPORT}" ;;
    platform)         echo "${INFISICAL_WS_PLATFORM}" ;;
    *)                echo "" ;;
  esac
}

# Partner-scoped workspace IDs (CUI needs these)
export INFISICAL_WS_ENGELMANN='${INFISICAL_WS_ENGELMANN}'
export INFISICAL_WS_WERKING_REPORT='${INFISICAL_WS_WERKING_REPORT}'
export INFISICAL_WS_PLATFORM='${INFISICAL_WS_PLATFORM}'
export INFISICAL_WS_DEV_SERVER='${INFISICAL_WS_DEV_SERVER}'

true
PARTNER_API

scp /tmp/partner-infisical-api.sh "root@$TARGET:$PARTNER_INFISICAL_DIR/infisical-api.sh"
rm -f /tmp/partner-infisical-api.sh
ssh "root@$TARGET" "chmod 644 $PARTNER_INFISICAL_DIR/infisical-api.sh && chown claude-user:claude-user $PARTNER_INFISICAL_DIR/infisical-api.sh"

# Also symlink to /root/.infisical/ (load-app-env checks there first)
ssh "root@$TARGET" "mkdir -p /root/.infisical && cp $PARTNER_INFISICAL_DIR/infisical-api.sh /root/.infisical/infisical-api.sh && cp $PARTNER_INFISICAL_DIR/get-token.py /root/.infisical/get-token.py && cp $PARTNER_INFISICAL_DIR/.auth-secret /root/.infisical/.auth-secret && chmod 600 /root/.infisical/.auth-secret"

# ── 5. Source from bashrc ───────────────────────────────────────────────
echo "[4/4] Adding to claude-user .bashrc..."
ssh "root@$TARGET" bash <<'REMOTE'
BASHRC="/home/claude-user/.bashrc"
MARKER="# Infisical API Helper"
if ! grep -q "$MARKER" "$BASHRC" 2>/dev/null; then
  echo "" >> "$BASHRC"
  echo "$MARKER" >> "$BASHRC"
  echo "[ -f /home/claude-user/.infisical/infisical-api.sh ] && source /home/claude-user/.infisical/infisical-api.sh" >> "$BASHRC"
fi
chown claude-user:claude-user "$BASHRC"
REMOTE

# ── 6. Verify ──────────────────────────────────────────────────────────
echo ""
echo "Verifying Infisical connectivity from partner..."
VERIFY=$(ssh "root@$TARGET" "su - claude-user -c 'source $PARTNER_INFISICAL_DIR/infisical-api.sh && infisical_get_secret \$INFISICAL_WS_ENGELMANN prod AI_BRIDGE_API_KEY'" 2>/dev/null) || true

echo ""
echo "========================================"
if [ -n "$VERIFY" ] && [ "$VERIFY" != "NOT_FOUND" ]; then
  echo "  INFISICAL SETUP SUCCESS"
  echo "  Partner can access secrets via Infisical"
  echo "  Workspace scope: engelmann, werking-report, platform, dev-server"
else
  echo "  INFISICAL SETUP WARNING"
  echo "  Could not verify secret access."
  echo "  Check: Tailscale connectivity to 100.79.71.99"
  echo "  Check: python3 + pyjwt installed on partner"
fi
echo "========================================"
