#!/bin/bash
# ============================================================================
# Code-Management Prerequisites — runs on the PARTNER server.
# ============================================================================
# Sets up the OS-level prerequisites for the /api/code-mgmt feature:
#   1. /etc/sudoers.d/cui-code-mgmt — claude-user can run git as any partner user
#   2. /opt/cui-workspace-data/proposals/ — proposals inbox, owned by claude-user
#
# Idempotent: safe to re-run after adding new partner users.
#
# USAGE (on partner, as root):
#   ./setup-code-mgmt.sh
#
# Reads partner usernames from /opt/cui-workspace-data/users.json (the canonical
# user list) and grants claude-user passwordless git for each one.
# ============================================================================
set -euo pipefail

if [ "$(id -u)" -ne 0 ]; then
  echo "ERROR: run as root" >&2
  exit 1
fi

USERS_JSON="${CUI_USERS_JSON:-/opt/cui-workspace-data/users.json}"
SUDOERS_FILE="/etc/sudoers.d/cui-code-mgmt"
PROPOSALS_DIR="/opt/cui-workspace-data/proposals"

if [ ! -f "$USERS_JSON" ]; then
  echo "ERROR: users.json not found at $USERS_JSON" >&2
  echo "       Run create-partner-users.sh first." >&2
  exit 1
fi

command -v jq >/dev/null || { echo "FATAL: jq missing — apt install jq" >&2; exit 1; }

echo "Reading users from $USERS_JSON …"
mapfile -t USER_IDS < <(jq -r '.users[] | select(.active != false) | .id' "$USERS_JSON")
echo "Found ${#USER_IDS[@]} users: ${USER_IDS[*]}"

# ── 1. Sudoers ──────────────────────────────────────────────────────────────
echo "Writing $SUDOERS_FILE …"
TMP_SUDO=$(mktemp)
{
  echo "# Code-Management — claude-user runs git on behalf of partner users."
  echo "# Generated by setup-code-mgmt.sh — do not edit by hand."
  echo "# Re-run setup-code-mgmt.sh after adding/removing partner users."
  for uid in "${USER_IDS[@]}"; do
    if id "$uid" &>/dev/null; then
      echo "claude-user ALL=($uid) NOPASSWD: /usr/bin/git"
    else
      echo "# (skipped: user '$uid' does not exist on this system)"
    fi
  done
} > "$TMP_SUDO"

# Validate via visudo before installing.
if visudo -cf "$TMP_SUDO" >/dev/null; then
  install -m 0440 -o root -g root "$TMP_SUDO" "$SUDOERS_FILE"
  rm -f "$TMP_SUDO"
  echo "  ✅ $SUDOERS_FILE installed"
else
  echo "  ❌ visudo validation failed — leaving $TMP_SUDO for inspection" >&2
  exit 1
fi

# ── 2. Proposals inbox ──────────────────────────────────────────────────────
echo "Setting up $PROPOSALS_DIR …"
install -d -m 0775 -o claude-user -g claude-user "$PROPOSALS_DIR"
echo "  ✅ $PROPOSALS_DIR ready (claude-user:claude-user 0775)"

# ── 3. Verify a sample sudo invocation works ───────────────────────────────
if [ ${#USER_IDS[@]} -gt 0 ]; then
  test_user="${USER_IDS[0]}"
  if id "$test_user" &>/dev/null; then
    echo "Verifying: sudo -u $test_user -n /usr/bin/git --version …"
    if sudo -u claude-user -- sudo -u "$test_user" -n /usr/bin/git --version >/dev/null 2>&1; then
      echo "  ✅ claude-user → $test_user git works"
    else
      echo "  ⚠️  claude-user → $test_user git failed — check sudoers rule" >&2
    fi
  fi
fi

echo ""
echo "Done. Restart the CUI server to pick up the new permissions:"
echo "  systemctl restart cui-server"
